#!/usr/bin/env python3
"""Regenerate cpp/tests/fk_reference.hpp from the vendored MJCF.

The point of the FK test is to compare against numbers this repository's own
kinematics did not produce, so the reference poses come from MuJoCo running on
`assets/franka/mjcf/panda.xml` rather than from the flattened chain JSON the
C++ core reads. `tests/test_urdf_mjcf_agree.py` separately establishes that the
two files describe the same robot, and quantifies the residual: 6.1e-12 m in
position and 8.4e-8 rad in orientation, the latter caused by Menagerie writing
body quaternions to seven decimal places. The tolerances in the C++ test admit
that and nothing larger.

Usage: python3 cpp/tests/make_fk_reference.py > cpp/tests/fk_reference.hpp
"""
import sys
from pathlib import Path

import mujoco
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
MJCF = ROOT / "assets/franka/mjcf/panda.xml"
HAND_TO_TCP_Z = 0.1034

# Four configurations: the arm folded, the neutral seed, and two that put every
# joint at a different sign and magnitude so a transposed or dropped fixed
# transform cannot pass by symmetry.
CONFIGURATIONS = [
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, -0.785398163397, 0.0, -2.35619449019, 0.0, 1.57079632679, 0.785398163397],
    [0.31, -0.62, 0.17, -2.11, 0.44, 1.83, -0.95],
    [-1.20, 0.75, 2.10, -1.05, -2.40, 2.60, 1.90],
]


def tcp_pose(model, data, hand_id, q):
    data.qpos[:7] = q
    mujoco.mj_kinematics(model, data)
    pose = np.eye(4)
    pose[:3, :3] = data.xmat[hand_id].reshape(3, 3)
    pose[:3, 3] = data.xpos[hand_id]
    offset = np.eye(4)
    offset[2, 3] = HAND_TO_TCP_Z
    return pose @ offset


def main() -> int:
    model = mujoco.MjModel.from_xml_path(str(MJCF))
    data = mujoco.MjData(model)
    hand_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "hand")

    out = sys.stdout
    out.write("#pragma once\n\n")
    out.write("// Generated by cpp/tests/make_fk_reference.py. Do not edit by hand.\n")
    out.write("// Base -> TCP poses computed by MuJoCo on assets/franka/mjcf/panda.xml,\n")
    out.write("// which is a different file and a different implementation from the\n")
    out.write("// flattened chain the C++ core reads.\n\n")
    out.write(f"constexpr int kFkCases = {len(CONFIGURATIONS)};\n")
    out.write("const double kFkQ[kFkCases][7] = {\n")
    for q in CONFIGURATIONS:
        out.write("  {" + ", ".join(repr(float(v)) for v in q) + "},\n")
    out.write("};\n")
    out.write("const double kFkTcpRowMajor[kFkCases][16] = {\n")
    for q in CONFIGURATIONS:
        pose = tcp_pose(model, data, hand_id, q)
        out.write("  {" + ", ".join(repr(float(v)) for v in pose.reshape(-1)) + "},\n")
    out.write("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
