#!/usr/bin/env python3
"""Drive both pipelines at fixed control rates and count what they miss.

The in-process benchmark answers "how long does one frame take". A control
loop asks a different question: given a period, how often is the answer late,
and by how much. Those are not the same question, because a pipeline whose p50
fits inside the period can still fall behind whenever the tail lands, and
because falling behind once delays the release of the next job.

The scheduler here is a real one, not a replay of recorded latencies. Every
job k is released at `origin + k * period` and is due at `origin + (k+1) *
period`, both computed from a single monotonic origin. Sleeping for
`period - work` each iteration instead would accumulate the sleep's own
overshoot into a drift of tens of milliseconds over a few hundred jobs, and
the drift would then be reported as jitter.

Overrun is not queued away. If job k finishes after job k+1 was due, job k+1
starts immediately and late, which is what a best-effort SensorDataQoS
subscriber does with a backlog it cannot clear (docs/ROS2.md). Both the
lateness at the start of a job and the lateness at its end are recorded.

Both implementations run under the same Python scheduler so the scheduler's
own cost and noise are charged equally. The C++ pipeline is reached through a
C ABI shim compiled against the same `libgrasp_core.a` that
`cpp/build/bench_pipeline` links, with the compile flags read out of the CMake
build tree so the shim cannot drift from the library. The latency reported for
a job is the pipeline's own `total_ns`, measured inside the pipeline by the
same instrumentation the in-process benchmark uses, so the ctypes call is not
inside it; the ctypes round trip is measured separately and reported in the
metadata so a reader can see what the scheduler's view of a job costs on top.

Usage:
  rate_sweep.py --out-dir results
  rate_sweep.py --dataset data/table_320x240 --rates 10 30 100 --jobs 100
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import platform
import re
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / 'python'))

DEFAULT_CONFIG = REPO_ROOT / 'assets' / 'pipeline_config.json'
STAGE_KEYS = ('decode', 'deproject', 'transform_crop', 'plane',
              'cluster', 'grasp', 'ik', 'traj')

# grasp_shim_run writes this many uint64 in this order.
RESULT_SLOTS = 15
NS_PER_S = 1_000_000_000

SHIM_SOURCE = r'''
// Generated by harness/rate_sweep.py. A C ABI over grasp_core::Pipeline so one
// Python scheduler can drive both implementations under identical release
// times. It adds no logic: every value it returns is one the pipeline already
// computed, and the timing it reports is the pipeline's own.
#include <cstdint>
#include "grasp_core/pipeline.hpp"

extern "C" {

void * grasp_shim_create(const char * config, const char * chain, const char * ransac)
{
  try {
    return new grasp_core::Pipeline(config, chain, ransac);
  } catch (...) {
    return nullptr;
  }
}

void grasp_shim_destroy(void * handle)
{
  delete static_cast<grasp_core::Pipeline *>(handle);
}

void grasp_shim_reserve(void * handle, int width, int height)
{
  static_cast<grasp_core::Pipeline *>(handle)->reserve(width, height);
}

double grasp_shim_timer_overhead_ns(void * handle)
{
  return static_cast<grasp_core::Pipeline *>(handle)->timer_overhead_ns();
}

// Calibrates the ctypes round trip: everything grasp_shim_run costs except the
// pipeline. Returns its argument so the call cannot be optimised away.
std::uint64_t grasp_shim_nop(std::uint64_t v)
{
  return v;
}

void grasp_shim_run(
  void * handle, const std::uint16_t * depth, const std::uint8_t * rgb,
  int width, int height, std::uint64_t * out)
{
  const grasp_core::Result & r =
    static_cast<grasp_core::Pipeline *>(handle)->run(depth, rgb, width, height);
  out[0] = r.total_ns;
  out[1] = r.stage_ns.decode;
  out[2] = r.stage_ns.deproject;
  out[3] = r.stage_ns.transform_crop;
  out[4] = r.stage_ns.plane;
  out[5] = r.stage_ns.cluster;
  out[6] = r.stage_ns.grasp;
  out[7] = r.stage_ns.ik;
  out[8] = r.stage_ns.traj;
  out[9] = static_cast<std::uint64_t>(r.points);
  out[10] = static_cast<std::uint64_t>(r.cluster_points);
  out[11] = static_cast<std::uint64_t>(r.iterations);
  out[12] = r.plane_found ? 1u : 0u;
  out[13] = r.graspable ? 1u : 0u;
  out[14] = r.converged ? 1u : 0u;
}

}  // extern "C"
'''


def die(message: str) -> None:
    print(f'rate_sweep: {message}', file=sys.stderr)
    raise SystemExit(1)


class FrameStore:
    """The corpus in RAM, as the byte buffers a subscriber would receive."""

    def __init__(self, directory: Path):
        manifest_path = directory / 'manifest.json'
        if not manifest_path.is_file():
            die(f'{manifest_path} does not exist; run harness/make_dataset.py')
        manifest = json.loads(manifest_path.read_text())
        self.directory = directory
        self.name = manifest['name']
        self.width = manifest['width']
        self.height = manifest['height']
        self.depth = [(directory / e['depth']).read_bytes()
                      for e in manifest['frames']]
        self.rgb = [(directory / e['rgb']).read_bytes()
                    for e in manifest['frames']]
        self.count = len(self.depth)


class Worker:
    """One implementation, bound to one frame store.

    `execute` does the work and nothing else: the scheduler brackets it with
    two clock reads, so anything that is not the pipeline must live in
    `collect`, which runs after the second read.
    """

    name = 'abstract'

    def execute(self, index: int) -> None:
        raise NotImplementedError

    def collect(self, row: np.ndarray) -> None:
        raise NotImplementedError

    def metadata(self) -> dict:
        return {}

    def close(self) -> None:
        pass


class PythonWorker(Worker):
    name = 'py'

    def __init__(self, store: FrameStore, config: Path, chain: Path,
                 ransac: Path):
        from grasp_core import GraspPipeline, calibrate_timer_ns
        self._pipeline = GraspPipeline(str(config), str(chain), str(ransac))
        self._pipeline.resize(store.height, store.width)
        self._timer = calibrate_timer_ns()
        self._result = None
        self._depth = store.depth
        self._rgb = store.rgb
        self._width = store.width
        self._height = store.height

    def execute(self, index: int) -> None:
        self._result = self._pipeline.run(
            self._depth[index], self._rgb[index], self._width, self._height)

    def collect(self, row: np.ndarray) -> None:
        result = self._result
        stage = result.stage_ns
        row[0] = result.total_ns
        for i, key in enumerate(STAGE_KEYS):
            row[1 + i] = stage[key]
        row[9] = result.points
        row[10] = result.cluster_points
        row[11] = result.iterations
        row[12] = result.plane_found
        row[13] = result.graspable
        row[14] = result.converged

    def metadata(self) -> dict:
        return {'timer_overhead_ns': self._timer['median_ns'],
                'numpy': np.__version__,
                'python': platform.python_version()}


def build_shim(build_dir: Path) -> Path:
    """Compile the C ABI shim with the flags the library itself was built with.

    Reading them out of the CMake build tree rather than restating them is the
    only way the shim and `libgrasp_core.a` cannot drift apart: a change to
    `cpp/CMakeLists.txt` reaches both or neither.
    """
    archive = build_dir / 'libgrasp_core.a'
    flags_file = build_dir / 'CMakeFiles' / 'grasp_core.dir' / 'flags.make'
    if not archive.is_file():
        die(f'{archive} does not exist; run\n'
            f'  cmake -S cpp -B {build_dir} -DCMAKE_BUILD_TYPE=Release && '
            f'cmake --build {build_dir} -j"$(nproc)"')
    if not flags_file.is_file():
        die(f'{flags_file} does not exist; the CMake build tree is incomplete')

    text = flags_file.read_text()
    compiler_match = re.search(r'^# compile CXX with (\S+)', text, re.M)
    flags_match = re.search(r'^CXX_FLAGS = (.*)$', text, re.M)
    includes_match = re.search(r'^CXX_INCLUDES = (.*)$', text, re.M)
    if not compiler_match or not flags_match:
        die(f'cannot read the compiler or flags out of {flags_file}')
    compiler = compiler_match.group(1)
    flags = flags_match.group(1).split()
    includes = (includes_match.group(1).split() if includes_match else [])

    source = build_dir / 'grasp_shim.cpp'
    library = build_dir / 'grasp_shim.so'
    source.write_text(SHIM_SOURCE)
    if (library.is_file()
            and library.stat().st_mtime > source.stat().st_mtime
            and library.stat().st_mtime > archive.stat().st_mtime):
        return library

    command = ([compiler] + flags + includes
               + ['-shared', '-fPIC', str(source), str(archive),
                  '-o', str(library)])
    completed = subprocess.run(command, capture_output=True, text=True)
    if completed.returncode != 0:
        die(f'compiling the shim failed:\n  {" ".join(command)}\n'
            f'{completed.stderr}')
    return library


class CppWorker(Worker):
    name = 'cpp'

    def __init__(self, store: FrameStore, config: Path, chain: Path,
                 ransac: Path, build_dir: Path):
        import ctypes
        self._ctypes = ctypes
        self._library_path = build_shim(build_dir)
        lib = ctypes.CDLL(str(self._library_path))
        lib.grasp_shim_create.restype = ctypes.c_void_p
        lib.grasp_shim_create.argtypes = [ctypes.c_char_p] * 3
        lib.grasp_shim_destroy.argtypes = [ctypes.c_void_p]
        lib.grasp_shim_reserve.argtypes = [ctypes.c_void_p, ctypes.c_int,
                                           ctypes.c_int]
        lib.grasp_shim_timer_overhead_ns.restype = ctypes.c_double
        lib.grasp_shim_timer_overhead_ns.argtypes = [ctypes.c_void_p]
        lib.grasp_shim_nop.restype = ctypes.c_uint64
        lib.grasp_shim_nop.argtypes = [ctypes.c_uint64]
        lib.grasp_shim_run.argtypes = [
            ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p,
            ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_uint64)]

        handle = lib.grasp_shim_create(
            str(config).encode(), str(chain).encode(), str(ransac).encode())
        if not handle:
            die(f'grasp_core::Pipeline refused to construct from {config}')
        lib.grasp_shim_reserve(handle, store.width, store.height)

        self._lib = lib
        self._handle = handle
        self._out = (ctypes.c_uint64 * RESULT_SLOTS)()
        self._depth = store.depth
        self._rgb = store.rgb
        self._width = store.width
        self._height = store.height
        self._run = lib.grasp_shim_run
        self._timer_overhead_ns = lib.grasp_shim_timer_overhead_ns(handle)
        self._call_overhead_ns = self._calibrate_call()

    def _calibrate_call(self, samples: int = 20000) -> float:
        """What the ctypes round trip costs, so it can be judged, not assumed.

        A no-op through the same CDLL and the same argument marshalling as
        grasp_shim_run, minus the pipeline.
        """
        nop = self._lib.grasp_shim_nop
        clock = time.perf_counter_ns
        started = clock()
        for i in range(samples):
            nop(i)
        elapsed = clock() - started
        # The Python loop is in there too, so this is an upper bound on the
        # call, which is the direction that keeps the claim honest.
        return elapsed / samples

    def execute(self, index: int) -> None:
        self._run(self._handle, self._depth[index], self._rgb[index],
                  self._width, self._height, self._out)

    def collect(self, row: np.ndarray) -> None:
        out = self._out
        for i in range(RESULT_SLOTS):
            row[i] = out[i]

    def metadata(self) -> dict:
        return {'timer_overhead_ns': self._timer_overhead_ns,
                'ctypes_call_overhead_ns': self._call_overhead_ns,
                'shim': str(self._library_path)}

    def close(self) -> None:
        if getattr(self, '_handle', None):
            self._lib.grasp_shim_destroy(self._handle)
            self._handle = None


def run_schedule(worker: Worker, store: FrameStore, jobs: int,
                 period_ns: int, warmup: int):
    """A fixed-period release schedule with absolute deadlines.

    Returns (release, start, finish, results) with all times in nanoseconds
    relative to the monotonic origin of the schedule.
    """
    clock = time.perf_counter_ns
    sleep = time.sleep
    count = store.count

    for k in range(warmup):
        worker.execute(k % count)

    release = np.empty(jobs, dtype=np.int64)
    start = np.empty(jobs, dtype=np.int64)
    finish = np.empty(jobs, dtype=np.int64)
    frames = np.empty(jobs, dtype=np.int64)
    results = np.zeros((jobs, RESULT_SLOTS), dtype=np.int64)

    origin = clock()
    for k in range(jobs):
        due = origin + k * period_ns
        now = clock()
        if now < due:
            sleep((due - now) / NS_PER_S)
            now = clock()
        index = (warmup + k) % count
        began = clock()
        worker.execute(index)
        ended = clock()
        release[k] = due - origin
        start[k] = began - origin
        finish[k] = ended - origin
        frames[k] = index
        worker.collect(results[k])

    return release, start, finish, frames, results


def percentiles(samples: np.ndarray, wanted, method: str) -> dict:
    if samples.size == 0:
        return {}
    # Same key names harness/analyze.py's stats() uses, so its table writer
    # can render a sweep run and a benchmark run without a special case.
    values = {f'p{p:g}': float(np.percentile(samples, p, method=method))
              for p in wanted}
    values['max'] = float(samples.max())
    values['mean'] = float(samples.mean())
    values['n'] = int(samples.size)
    return values


def summarise(impl: str, store: FrameStore, rate_hz: float, period_ns: int,
              release, start, finish, results, wanted, method: str) -> dict:
    total = results[:, 0]
    deadline = release + period_ns
    overrun = finish - deadline
    start_delay = start - release
    response = finish - release
    misses = int((overrun > 0).sum())
    jobs = int(total.size)

    return {
        'impl': impl,
        'dataset': store.name,
        'width': store.width,
        'height': store.height,
        'pixels': store.width * store.height,
        'rate_hz': rate_hz,
        'period_ms': period_ns / 1e6,
        'jobs': jobs,
        'deadline_misses': misses,
        'deadline_miss_rate': misses / jobs,
        'compute': percentiles(total, wanted, method),
        'response': percentiles(response, wanted, method),
        # Signed on purpose: a negative worst case says the slowest job of
        # the run still finished that far before its deadline.
        'worst_finish_vs_deadline_ms': float(overrun.max()) / 1e6,
        'worst_finish_vs_deadline_periods': float(overrun.max()) / period_ns,
        'worst_start_vs_release_ms': float(start_delay.max()) / 1e6,
        'utilisation': float(total.mean()) / period_ns,
        'sustainable_hz_p50': NS_PER_S / float(
            np.percentile(total, 50.0, method=method)),
        'sustainable_hz_p99': NS_PER_S / float(
            np.percentile(total, 99.0, method=method)),
        'bail_outs': {
            'plane_not_found': int((results[:, 12] == 0).sum()),
            'not_graspable': int((results[:, 13] == 0).sum()),
            'ik_not_converged': int((results[:, 14] == 0).sum()),
        },
        'stage_p50_ns': {key: float(np.percentile(results[:, 1 + i], 50.0,
                                                  method=method))
                         for i, key in enumerate(STAGE_KEYS)},
        # Recorded per run because four shared vCPUs mean a neighbour's work
        # lands in this run's tail, and a reader deserves to see when a row
        # was taken under load rather than having to trust that it was not.
        'load_average_at_end': list(os.getloadavg()),
    }


def onset(runs: list[dict]) -> list[dict]:
    """The rate at which each implementation starts missing deadlines."""
    out = []
    keys = sorted({(r['impl'], r['dataset']) for r in runs})
    for impl, dataset in keys:
        rows = sorted((r for r in runs
                       if r['impl'] == impl and r['dataset'] == dataset),
                      key=lambda r: r['rate_hz'])
        clean = [r['rate_hz'] for r in rows if r['deadline_misses'] == 0]
        missing = [r['rate_hz'] for r in rows if r['deadline_misses'] > 0]
        out.append({
            'impl': impl,
            'dataset': dataset,
            'highest_clean_rate_hz': max(clean) if clean else None,
            'lowest_missing_rate_hz': min(missing) if missing else None,
            # The slowest observation across the swept rates, because
            # compute latency is not identical at every rate: idling between
            # jobs at 10 Hz costs cache residency that a saturated loop keeps.
            'sustainable_hz_p50': min(r['sustainable_hz_p50'] for r in rows),
            'sustainable_hz_p99': min(r['sustainable_hz_p99'] for r in rows),
            'note': ('no swept rate ran clean' if not clean else
                     'no swept rate missed a deadline' if not missing else ''),
        })
    return out


CSV_COLUMNS = ('impl', 'dataset', 'width', 'height', 'pixels', 'rate_hz',
               'period_ms', 'jobs', 'deadline_misses', 'deadline_miss_rate',
               'compute_p50_ms', 'compute_p95_ms', 'compute_p99_ms',
               'compute_max_ms', 'compute_mean_ms',
               'response_p50_ms', 'response_p99_ms', 'response_max_ms',
               'worst_finish_vs_deadline_ms', 'worst_start_vs_release_ms',
               'worst_finish_vs_deadline_periods', 'utilisation', 'sustainable_hz_p50', 'sustainable_hz_p99')


def csv_rows(runs: list[dict]):
    for run in runs:
        compute, response = run['compute'], run['response']
        yield {
            'impl': run['impl'],
            'dataset': run['dataset'],
            'width': run['width'],
            'height': run['height'],
            'pixels': run['pixels'],
            'rate_hz': f"{run['rate_hz']:g}",
            'period_ms': f"{run['period_ms']:.4f}",
            'jobs': run['jobs'],
            'deadline_misses': run['deadline_misses'],
            'deadline_miss_rate': f"{run['deadline_miss_rate']:.6f}",
            'compute_p50_ms': f"{compute['p50'] / 1e6:.4f}",
            'compute_p95_ms': f"{compute['p95'] / 1e6:.4f}",
            'compute_p99_ms': f"{compute['p99'] / 1e6:.4f}",
            'compute_max_ms': f"{compute['max'] / 1e6:.4f}",
            'compute_mean_ms': f"{compute['mean'] / 1e6:.4f}",
            'response_p50_ms': f"{response['p50'] / 1e6:.4f}",
            'response_p99_ms': f"{response['p99'] / 1e6:.4f}",
            'response_max_ms': f"{response['max'] / 1e6:.4f}",
            'worst_finish_vs_deadline_ms':
                f"{run['worst_finish_vs_deadline_ms']:.4f}",
            'worst_start_vs_release_ms':
                f"{run['worst_start_vs_release_ms']:.4f}",
            'worst_finish_vs_deadline_periods':
                f"{run['worst_finish_vs_deadline_periods']:.3f}",
            'utilisation': f"{run['utilisation']:.4f}",
            'sustainable_hz_p50': f"{run['sustainable_hz_p50']:.2f}",
            'sustainable_hz_p99': f"{run['sustainable_hz_p99']:.2f}",
        }


def plot(runs: list[dict], path: Path) -> None:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    datasets = sorted({r['dataset'] for r in runs},
                      key=lambda name: next(x['pixels'] for x in runs
                                            if x['dataset'] == name))
    colours = {'cpp': '#1f4e79', 'py': '#c0504d'}
    # Distinct markers because the two miss-rate curves sit on top of each
    # other at 0% and at 100%, and a hidden curve is a misread plot.
    markers = {'cpp': 'o', 'py': 's'}
    dashes = ['-', '--', ':', '-.']

    figure, axes = plt.subplots(2, 1, figsize=(8.0, 8.0), sharex=True)
    upper, lower = axes

    for d_index, dataset in enumerate(datasets):
        style = dashes[d_index % len(dashes)]
        for impl in ('cpp', 'py'):
            rows = sorted((r for r in runs if r['impl'] == impl
                           and r['dataset'] == dataset),
                          key=lambda r: r['rate_hz'])
            if not rows:
                continue
            rates = [r['rate_hz'] for r in rows]
            p50 = [r['compute']['p50'] / 1e6 for r in rows]
            p99 = [r['compute']['p99'] / 1e6 for r in rows]
            label = f'{impl} {dataset.replace("table_", "")}'
            upper.plot(rates, p50, style, color=colours[impl],
                       marker=markers[impl], markersize=5, label=label)
            upper.fill_between(rates, p50, p99, color=colours[impl],
                               alpha=0.12, linewidth=0)
            lower.plot(rates, [100.0 * r['deadline_miss_rate'] for r in rows],
                       style, color=colours[impl], marker=markers[impl],
                       markersize=5, markerfacecolor='none', label=label)

    rates = sorted({r['rate_hz'] for r in runs})
    upper.plot(rates, [1000.0 / r for r in rates], color='0.35',
               linewidth=1.0, linestyle=(0, (6, 3)),
               label='control period (the budget)')
    upper.set_xscale('log')
    upper.set_yscale('log')
    upper.set_ylabel('pipeline latency, ms\n(p50 line, p50 to p99 shaded)')
    upper.set_title('Latency against control rate, and what it costs in misses')
    upper.grid(True, which='both', alpha=0.25)
    upper.legend(fontsize=8, loc='upper right', ncol=2)

    lower.set_xscale('log')
    lower.set_xlabel('control rate, Hz')
    lower.set_ylabel('deadline misses, %')
    lower.set_ylim(-4, 104)
    lower.set_xticks(rates)
    lower.set_xticklabels([f'{r:g}' for r in rates])
    lower.grid(True, which='both', alpha=0.25)

    figure.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=150)
    plt.close(figure)


def main(argv=None) -> int:
    config_text = DEFAULT_CONFIG.read_text()
    config = json.loads(config_text)
    sweep = config['rate_sweep']
    analysis = config['analysis']

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--dataset', type=Path, action='append', default=None,
                        help='frame store directory; repeatable. Defaults to '
                             'rate_sweep.datasets in the config')
    parser.add_argument('--data-root', type=Path, default=REPO_ROOT / 'data')
    parser.add_argument('--impl', action='append', default=None,
                        choices=('cpp', 'py'),
                        help='repeatable; defaults to both')
    parser.add_argument('--rates', type=float, nargs='+',
                        default=sweep['rates_hz'])
    parser.add_argument('--jobs', type=int, default=sweep['jobs_per_rate'])
    parser.add_argument('--warmup', type=int, default=sweep['warmup_jobs'])
    parser.add_argument('--out-dir', type=Path, default=REPO_ROOT / 'results')
    parser.add_argument('--build-dir', type=Path,
                        default=REPO_ROOT / 'cpp' / 'build')
    parser.add_argument('--config', type=Path, default=DEFAULT_CONFIG)
    parser.add_argument('--chain', type=Path,
                        default=REPO_ROOT / 'assets' / 'franka' / 'panda_chain.json')
    parser.add_argument('--ransac-table', type=Path,
                        default=REPO_ROOT / 'assets' / 'ransac_uniform.bin')
    parser.add_argument('--no-plot', action='store_true')
    args = parser.parse_args(argv)

    directories = args.dataset or [args.data_root / name
                                   for name in sweep['datasets']]
    implementations = args.impl or ['cpp', 'py']
    wanted = analysis['percentiles']
    method = analysis['percentile_method']

    runs: list[dict] = []
    worker_metadata: dict[str, dict] = {}

    for directory in directories:
        store = FrameStore(Path(directory))
        for impl in implementations:
            if impl == 'cpp':
                worker = CppWorker(store, args.config, args.chain,
                                   args.ransac_table, args.build_dir)
            else:
                worker = PythonWorker(store, args.config, args.chain,
                                      args.ransac_table)
            worker_metadata[impl] = worker.metadata()
            try:
                for rate in args.rates:
                    period_ns = int(round(NS_PER_S / rate))
                    release, start, finish, _frames, results = run_schedule(
                        worker, store, args.jobs, period_ns, args.warmup)
                    run = summarise(impl, store, rate, period_ns, release,
                                    start, finish, results, wanted, method)
                    runs.append(run)
                    print(f"{impl:>4} {store.name:<16} {rate:>6.1f} Hz  "
                          f"p50 {run['compute']['p50'] / 1e6:7.2f} ms  "
                          f"p99 {run['compute']['p99'] / 1e6:7.2f} ms  "
                          f"misses {100 * run['deadline_miss_rate']:5.1f}%  "
                          f"worst finish "
                          f"{run['worst_finish_vs_deadline_periods']:+6.2f} "
                          f"periods vs deadline", flush=True)
            finally:
                worker.close()

    report = {
        'metadata': {
            'generated_at_utc': time.strftime('%Y-%m-%dT%H:%M:%SZ',
                                              time.gmtime()),
            'scheduler': 'absolute deadlines from one monotonic origin, '
                         'time.perf_counter_ns',
            'jobs_per_rate': args.jobs,
            'warmup_jobs': args.warmup,
            'rates_hz': list(args.rates),
            'percentile_method': method,
            'workers': worker_metadata,
            'host': {
                'platform': platform.platform(),
                'cpu_count': os.cpu_count(),
                'load_average': list(os.getloadavg()),
            },
        },
        'runs': runs,
        'onset': onset(runs),
    }

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / 'rate_sweep.json').write_text(
        json.dumps(report, indent=2) + '\n', encoding='utf-8')
    with (args.out_dir / 'rate_sweep.csv').open('w', newline='',
                                                encoding='utf-8') as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(csv_rows(runs))
    if not args.no_plot:
        plot(runs, args.out_dir / 'rate_sweep.png')

    print(f'wrote {args.out_dir}/rate_sweep.json, rate_sweep.csv'
          + ('' if args.no_plot else ', rate_sweep.png'))
    for row in report['onset']:
        clean = row['highest_clean_rate_hz']
        print(f"  {row['impl']:>4} {row['dataset']:<16} "
              f"highest clean rate "
              f"{'none swept' if clean is None else f'{clean:g} Hz'}, "
              f"sustainable from p99 {row['sustainable_hz_p99']:.1f} Hz")
    return 0


if __name__ == '__main__':
    sys.exit(main())
